"""empty message

Revision ID: f819f3f77f30
Revises: None
Create Date: 2016-09-18 14:43:29.396514

"""

# revision identifiers, used by Alembic.
revision = 'f819f3f77f30'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortenedURL',
    sa.Column('alias', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=2083), nullable=True),
    sa.PrimaryKeyConstraint('alias'),
    sa.UniqueConstraint('target')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortenedURL')
    ### end Alembic commands ###
