# -*- coding: utf-8 -*-

import unittest
from unittest.mock import Mock, patch

from nose_parameterized import parameterized

from url_shortener import (
    Alias, AliasValueError, IntegerAlias, _get_min_value, _get_max_value,
    AliasLengthValueError
)


class GetMinValueTest(unittest.TestCase):
    @parameterized.expand([
        ('two_digit_binary', 2, 2, 2),
        ('three_digit_decimal', 10, 3, 100),
    ])
    def test_get_min_value_of_(self, _, base, digit_number, expected):
        self.assertEqual(expected, _get_min_value(base, digit_number))


class GetMaxValueTest(unittest.TestCase):
    @parameterized.expand([
        ('two_digit_binary', 2, 2, 3),
        ('three_digit_decimal', 10, 3, 999),
    ])
    def test_get_max_value_of_(self, _, base, digit_number, expected):
        self.assertEqual(expected, _get_max_value(base, digit_number))


class AliasTest(unittest.TestCase):
    ''' Tests for Alias class

    :var ALIAS_INTEGER: maps string values of aliases used in tests to
    corresponding integers.
    :var INTEGERS: a list of lists, each containing one of the integers
    specified in ALIAS_INTEGER. Used as an argument for
    parameterized.expand()
    :var ALIASES_TO_INTEGERS: a list containing tuples, each with a pair of
    alias string and its corresponding integer. Used as an argument for
    parameterized.expand()
    '''
    ALIAS_INTEGER = {
        'baa': 1*3**2,
        'ccb': 2*3**2+2*3+1,
        'caca': 2*3**3+2*3,
        'ccc': 2*3**2+2*3+2,
        'a': 0
    }
    INTEGERS = [[v] for v in ALIAS_INTEGER.values()]
    ALIASES_TO_INTEGERS = ALIAS_INTEGER.items()

    @classmethod
    def setUpClass(cls):
        Alias._CHARS = 'abc'
        Alias._BASE = 3

    def setUp(self):
        self.get_min_value_patcher = patch('url_shortener._get_min_value')
        self.get_min_value_mock = self.get_min_value_patcher.start()
        self.get_min_value_mock.return_value = 1
        self.get_max_value_patcher = patch('url_shortener._get_max_value')
        self.get_max_value_mock = self.get_max_value_patcher.start()
        self.get_max_value_mock.return_value = 2**31-10

    def tearDown(self):
        self.get_min_value_patcher.stop()
        self.get_max_value_patcher.stop()

    def test_init_for_invalid_string(self):
        ''' The string contains forbidden characters '''
        string = 'abcd'
        self.assertRaises(AliasValueError, Alias, None, string)

    def test_init_for_invalid_arg_set(self):
        ''' The arguments integer and string can't both be None '''
        self.assertRaises(AliasValueError, Alias, None, None)

    @parameterized.expand(ALIASES_TO_INTEGERS)
    def test_init_for_generated_integer(self, string, expected_integer):
        ''' The integer value of alias should be properly calculated
        when integer == None '''
        instance = Alias(string=string)
        actual_integer = instance.integer
        self.assertEqual(expected_integer, actual_integer)

    @parameterized.expand(INTEGERS)
    def test_init_for_string_being_none(self, integer):
        ''' The string value should not be generated during
        object initialization'''
        instance = Alias(integer=integer)
        self.assertIsNone(instance._string)

    @parameterized.expand(ALIASES_TO_INTEGERS)
    def test_str_for_string_being_none(self, expected_string, integer):
        ''' The __str__ method should properly generate string
        based on objects .integer property '''
        instance = Alias(integer=integer)
        actual_string = str(instance)
        self.assertEqual(expected_string, actual_string)

    @parameterized.expand([
        ('min_length_less_than_zero', -1, 3),
        ('min_and_max_length_less_than_zero', -3, -2),
        ('max_length_less_than_zero', 1, -1),
        ('max_length_less_than_min', 3, 2)
    ])
    def test_random_factory_for(self, _, min_length, max_length):
        ''' Alias.random_factory expects two arguments: min_length
        and max_length, referring to minimum and maximum lengths
        for aliases generated by function it returns.

        If any of these values is smaller than zero, or if the
        minimum value is larger than the maximum one,
        AliasLengthValueError is expected to be raised
        '''
        self.assertRaises(
            AliasLengthValueError,
            Alias.random_factory,
            min_length,
            max_length
        )

    @parameterized.expand([
        ('larger_than_max_int_32', 2**32, 2**31-10),
        ('for_max_length_larger_than_int_32', 2**31-10, 2**32)
    ])
    def test_random_factory_for_min_int(
            self,
            _,
            min_int,
            min_int_for_max_length
    ):
        ''' Alias.random_factory receives lower and upper limits
        for length of string representation of new aliases as
        its arguments. For these values to be usable, there must be
        integer values that:
        * correspond to string values in these limits
        * are smaller than maximum 32 bit signed integer

        If no such integer exists even for the shortest aliases,
        the whole range of length of alias strings is not available
        for new instances of Alias.
        If no such integers exist for the longest alias strings,
        only part of the range is available.

        In both cases, AliasLengthValueError is expected to be raised
        '''
        min_length = 1
        max_length = 4

        def get_min_value(_, digit_number):
            min_values = {
                min_length: min_int,
                max_length: min_int_for_max_length
            }
            return min_values.get(digit_number)

        self.get_min_value_mock.side_effect = get_min_value
        self.assertRaises(
            AliasLengthValueError,
            Alias.random_factory,
            min_length,
            max_length
        )

    @parameterized.expand([
        ('smaller_than_max_int_32', 2**31-4),
        ('larger_than_max_int_32', 2**32)
    ])
    @patch('url_shortener.randint')
    def test_random_factory_for_max_int(self, _, max_int, randint_mock):
        '''Alias.random_factory calculates lower and upper limits for
        integer representation of instances of Alias to be created by
        the function the method returns.

        The maximum integer can't be larger than maximum value of
        32-bit signed integer. If the max value of integer based only
        on maximum length of string representation of Alias is smaller
        than maximum int32, it is used by the factory function.
        If it's not, maximum int32 is used instead
        '''
        expected_min_int = 3
        self.get_min_value_mock.return_value = expected_min_int
        max_int_32 = 2**31-1
        expected_max_int = min(max_int_32, max_int)
        self.get_max_value_mock.return_value = max_int

        factory = Alias.random_factory(1, 4)
        factory()

        randint_mock.assert_called_once_with(
            expected_min_int,
            expected_max_int
        )

    @parameterized.expand([
        ('non-equal', 1, 3),
        ('equal', 2, 2)
    ])
    def test_random_factory_for_args(self, _, min_length, max_length):
        '''The Alias.random_factory class method is expected to return
        a callable object for correct arguments
        '''
        result = Alias.random_factory(min_length, max_length)
        self.assertTrue(callable(result))


class IntegerAliasTest(unittest.TestCase):
    ''' Tests for IntegerAlias class

    :var tested_instance: an instance of the class to be tested
    :var value: a mock used as value parameter to be passed
    to tested methods
    :var dialect: a mock used as dialect parameter to be passed
    to tested methods
    '''
    def setUp(self):
        self.tested_instance = IntegerAlias()
        self.value = Mock()
        self.dialect = Mock()

    @parameterized.expand([
        ['process_bind_param'],
        ['process_literal_param']
    ])
    def test_(self, method_name):
        ''' The method should return an integer value of the
        Alias object passed to them as value param
        '''
        function = getattr(self.tested_instance, method_name)
        expected = self.value.integer
        actual = function(self.value, self.dialect)
        self.assertEqual(expected, actual)

    @patch('url_shortener.Alias')
    def test_process_result_value(self, patched_alias_class):
        ''' The process_result_value method should return an
        instance of Alias
        '''
        expected = patched_alias_class(integer=self.value)
        actual = self.tested_instance.process_result_value(
            self.value,
            self.dialect
        )
        self.assertEqual(expected, actual)


if __name__ == "__main__":
    # import sys;sys.argv = ['', 'Test.testName']
    unittest.main()
